### ISSUE TITLE
[question] Does BiomesOPlenty or Terralith stop the spawn of your biomes ?

### ISSUE THREAD

**Issue by Zygus42** [dragoni7/Dreamland-1.19.2#1]
Am using:
Dreamland-forge-1.19.2-1.1.1
geckolib-forge-1.19-3.1.16
BiomesOPlenty-1.19.2-17.1.1.150
TerraBlender-forge-1.19.2-2.0.1.125
Terralith_v2.3.3
forge-1.19.2-43.0.19-installer

The mod is working, but the biomes are not showing on the biomes list.  Would have thought BoP and Dreamlands would work together fine as they both use TerraBlender.  I looked in the configs for all these mods, but nothing there seems relevant.  Am i missing something blindingly obvious ?

**Comment by dragoni7** [comment]
I tried replicating this myself and couldn't seem to recreate the issue. /locate biome dreamland:hive should work.
