### ISSUE TITLE
Breaking a door on its top block drops 2 doors instead of just 1

### ISSUE THREAD

**Issue by Not-February** [dragoni7/Dreamland-1.19.2#3]
First I would just like to say I'm so happy to see this mod's continued development - I love fantasy/unusual kinds of biomes so I've been keeping an eye on this mod for a little while now. I just recently had the chance to sit down and load up a world with it, and I'm definitely excited to see whatever else you have planned for this project going forward.

With that out of the way, I briefly loaded up a single player world in survival mode to tinker around a bit while I had the time, and discovered that breaking a Plum Birch Door by the top block will actually cause both the top and bottom to drop a door - you end up with two instead of just the one.

It's possible this is also happening with other doors from the mod too, but I haven't tested that personally.

Minecraft 1.19.2
Forge 43.1.25
Dreamland Biomes 1.2.0

**Comment by dragoni7** [comment]
Thanks for reporting this. When I made the loot tables for doors I did it wrong, it's fixed now and will be in the next update shortly
