### ISSUE TITLE
Dreamlands on Server Causing Chunk Corruption

### ISSUE THREAD

**Issue by Zelioth** [dragoni7/Dreamland-1.19.2#4]
I have a dedicated modpack and server that has been operational for some time now. This mod has been included since the day I created both pack and server. There hasn't seemed to be an issue till recently. 

Mod Pack :[](https://www.curseforge.com/minecraft/modpacks/friends-united)
Minecraft Versions 1.19.2
Forge Version : 43.1.25
Mod Version : 1.19.2-1.2.0 Beta

The version 1.1.1 Beta seemed to not have this issue but as of recently we are getting players who enter Dream Lands Biomes getting disconnected and the server reporting chunk errors and player Pars error. 

The entire Log is too large so i will just post a small versions with the player who was stuck in the chunk. 
[Friends United Server Log Error DreamLands.txt](https://github.com/dragoni7/Dreamland-1.19.2/files/9557618/Friends.United.Server.Log.Error.DreamLands.txt)

If you happen to think there is another issue at play here please further explain. The player entered the dreamlands biomes, said they 

"I was in the tar and I got a sort of portal using stutter and then it crashed me out instead of teleporting
I thought it might be teleporting me"

This was referenced directly from the player. also a server restart was done to see if anything had changed. once started and logged in again nothing had changed, player was still stuck and could not connect due to "dreamland.network.Networking.sendToServer" and her client saying "Interal Server Error"

**Comment by Zelioth** [comment]
> I have a dedicated modpack and server that has been operational for some time now. This mod has been included since the day I created both pack and server. There hasn't seemed to be an issue till recently.
> 
> Mod Pack : Minecraft Versions 1.19.2 Forge Version : 43.1.25 Mod Version : 1.19.2-1.2.0 Beta
> 
> The version 1.1.1 Beta seemed to not have this issue but as of recently we are getting players who enter Dream Lands Biomes getting disconnected and the server reporting chunk errors and player Pars error.
> 
> The entire Log is too large so i will just post a small versions with the player who was stuck in the chunk. [Friends United Server Log Error DreamLands.txt](https://github.com/dragoni7/Dreamland-1.19.2/files/9557618/Friends.United.Server.Log.Error.DreamLands.txt)
> 
> If you happen to think there is another issue at play here please further explain. The player entered the dreamlands biomes, said they
> 
> "I was in the tar and I got a sort of portal using stutter and then it crashed me out instead of teleporting I thought it might be teleporting me"
> 
> This was referenced directly from the player. also a server restart was done to see if anything had changed. once started and logged in again nothing had changed, player was still stuck and could not connect due to "dreamland.network.Networking.sendToServer" and her client saying "Interal Server Error"

I see for some reason it didn't let me post the link to the mod pack

https://www.curseforge.com/minecraft/modpacks/friends-united

**Comment by dragoni7** [comment]
Unable to replicate
