### ISSUE TITLE
[1.19.2 Forge] Modpack Crash caused by Dreamland?

### ISSUE THREAD

**Issue by RedBeast1959** [dragoni7/Dreamland-1.19.2#5]
Forge 43.1.43
Dreamland-forge-1.19.2-1.2.0.2.jar
TerraBlender-forge-1.19.2-2.0.1.128.jar
geckolib-forge-1.19-3.1.27.jar
Decorative Blocks-forge-1.19.2-3.0.0.jar
Wandering Trapper-forge-1.19.2-2.0.0.jar
musketmod-1.19.2-forge-1.4.5.jar
+@

Crash Report
[crash-2022-10-19_01.25.55-client.txt](https://github.com/dragoni7/Dreamland-1.19.2/files/9812755/crash-2022-10-19_01.25.55-client.txt)
[crash-2022-10-19_01.32.39-client.txt](https://github.com/dragoni7/Dreamland-1.19.2/files/9812756/crash-2022-10-19_01.32.39-client.txt)

Latest.log
[latest.log](https://github.com/dragoni7/Dreamland-1.19.2/files/9812758/latest.log)

**Comment by dragoni7** [comment]
Thanks for bringing this up. Working on a fix, should be in the next update
