### ISSUE TITLE
Bonemeal

### ISSUE THREAD

**Issue by gremlinninatree** [dragoni7/Dreamland-1.19.2#8]
Hi! I can't bonemeal the ground in the jewel forest as well as the shrubs to make trees, so I was just wondering if you could add the bonemeal functions? Thank you :>

**Comment by dragoni7** [comment]
Yes seems like I forgot to add bone meal functionality to the grass. As for the shrubs they are just meant as decorative plants, so in order to get the trees you need the saplings which drop from the leaves as usual.
This will be fixed in the next update :)
